version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # check npm dependencies for security risks - run 'npm audit' to fix
      - run:
          name: Security Check
          command: npx audit-ci --moderate --report-type full --skip-dev

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # ensure code formatting standards are adhered to - run 'npm run standardize' to fix
      - run:
          name: Check for Code Style and Linting Issues
          command: |
            npm run style
            npm run lint

      - run:
          name: Run Tests and Check Code Coverage
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test_results/
      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage

      # upload coverage report to coveralls for readme badge support
      # requires config.yml version 2.1 and orbs: coveralls: coveralls/coveralls@1.0.4
      # requires coveralls account and token specific to repo to be stored in CircleCI
      #- coveralls/upload

      - run: npm run build
      - run: npm pack

      - run: cp *.tgz /tmp/circle-artifacts
      - store_artifacts:
          path: /tmp/circle-artifacts
          destination: angular-unit-test-helper.tgz
      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/pkg
            mv *.tgz /tmp/workspace/pkg/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pkg
  deploy:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish $(echo /tmp/workspace/pkg/*.tgz)
workflows:
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy:
          context: npm
          requires:
            - hold
